jenkins:
  host: http://172.16.0.62:19011
  username: admin
  token: 1178b9a119547892acc981e7246e8360f3

sonar:
  host: localhost:9000
  token: Basic YzM5MzgxNGIyMjRlYzFkNGU5ZDAzMTdjYjNkMGFlODg0NzljZDgzMzo=
  codes:
    - squid:S2259
    - squid:S3986
    - squid:S2111
    - squid:S4973
    - squid:S2583
    - squid:S2119
    - squid:S2095
    - pmd:OverrideBothEqualsAndHashcode

scanner:
  dir: D:\\scanner
