jenkins:
  host: localhost:8080
  username: admin
  token: 1178b9a119547892acc981e7246e8360f3

sonar:
  host: 172.16.0.62:11190
  token: Basic YzEyZGIwNTNmYjEyZjIwZTE4YTQyYzVlMTYyODk1NDFlYmE5MzA4Yzo=
  codes:
    - squid:S2259
    - squid:S3986
    - squid:S2111
    - squid:S4973
    - squid:S2583
    - squid:S2119
    - squid:S2095
    - pmd:OverrideBothEqualsAndHashcode

scanner:
  dir: D:\\scanner

debug: true
